apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    name: nginx
spec:
  containers:
    - name: nginx
      image: nginx
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 80
      volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf # needed so that the ConfigMap is mounted as a file, not a directory

  volumes:
    - name: nginx-config
      configMap:
        name: nginx-config
        items:
          - key: nginx.conf
            path: nginx.conf
