apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv01
spec:
  storageClassName: adminmstorage
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  # hostPath is specific to Minikube
  hostPath:
    path: /data/pv01
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
spec:
  storageClassName: adminmstorage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: storagedemo
  labels:
    name: pvcdemo
spec:
  containers:
    - name: democontainer
      image: nginx:latest
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 80
      volumeMounts:
        - name: pvstor
          mountPath: "/usr/share/nginx/html"
  volumes:
    - name: pvstor
      persistentVolumeClaim:
        claimName: mypvc
