apiVersion: v1
kind: Pod
metadata:
  name: myweb
  labels:
    server: web
spec:
  containers:
  - name: myweb
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80